dubbo-provider:
  service:
    version: 1.0.0
nacos:
  host: 192.168.42.7
  port: 8848
  username: nacos
  password: nacos
spring:
  application:
    name: hello-spring-cloud-alibaba-dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.42.7:8848
dubbo:
  protocol:
    serialization: kryo
  registry:
    address: nacos://${nacos.host}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
server:
  port: 8081
