dubbo-provider:
  service:
    version: 1.0.0
nacos:
  host: 192.168.42.7
  port: 8848
  username: nacos
  password: nacos
spring:
  application:
    name: hello-spring-cloud-alibaba-dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.42.7:8848
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
dubbo:
  protocol:
    serialization: kryo
  registry:
    address: nacos://${nacos.host}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
  scan:
    base-packages: com.demo.hello.spring.cloud.alibaba.dubbo.consumer.service
server:
  # 随机端口
#  port: ${random.int[9000,9999]}
  port: 8081
