dubbo-provider:
  service:
    version: 1.0.0
nacos:
  host: 192.168.42.7
  port: 8848
  username: nacos
  password: nacos
spring:
  application:
    name: hello-spring-cloud-alibaba-dubbo-provider-service
dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
  scan:
    base-packages: com.demo.hello.spring.cloud.alibaba.dubbo.provider.service.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  #均衡策略
  provider:
    loadbalance: roundrobin